
title: 5zzang
url: 'https://www.5zzang.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Taewoo(Michael) Kim  ## put your name
title: 'DevOps Architect'  ## your title
location: South Korea


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: #  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
